// Interface for language options in Quick Pick
interface LanguageOption {
	label: string;
	description: string;
	languageCode: string;
}

// Comprehensive list of supported languages for map labels
export const LANGUAGE_OPTIONS: LanguageOption[] = [
	{ label: 'Native (Local)', description: 'Use native/local place names', languageCode: 'native' },
	{ label: 'English', description: 'English', languageCode: 'en' },
	{ label: 'German', description: 'Deutsch', languageCode: 'de' },
	{ label: 'French', description: 'Français', languageCode: 'fr' },
	{ label: 'Spanish', description: 'Español', languageCode: 'es' },
	{ label: 'Russian', description: 'Русский', languageCode: 'ru' },
	{ label: 'Chinese (Simplified)', description: '简体中文', languageCode: 'zh-Hans' },
	{ label: 'Chinese (Traditional)', description: '繁體中文', languageCode: 'zh-Hant' },
	{ label: 'Japanese', description: '日本語', languageCode: 'ja' },
	{ label: 'Korean', description: '한국어', languageCode: 'ko' },
	{ label: 'Italian', description: 'Italiano', languageCode: 'it' },
	{ label: 'Portuguese', description: 'Português', languageCode: 'pt' },
	{ label: 'Portuguese (Brazil)', description: 'Português (Brasil)', languageCode: 'pt-BR' },
	{ label: 'Arabic', description: 'العربية', languageCode: 'ar' },
	{ label: 'Hindi', description: 'हिन्दी', languageCode: 'hi' },
	{ label: 'Dutch', description: 'Nederlands', languageCode: 'nl' },
	{ label: 'Polish', description: 'Polski', languageCode: 'pl' },
	{ label: 'Turkish', description: 'Türkçe', languageCode: 'tr' },
	{ label: 'Indonesian', description: 'Bahasa Indonesia', languageCode: 'id' },
	{ label: 'Vietnamese', description: 'Tiếng Việt', languageCode: 'vi' },
	{ label: 'Thai', description: 'ไทย', languageCode: 'th' },
	{ label: 'Greek', description: 'Ελληνικά', languageCode: 'el' },
	{ label: 'Czech', description: 'Čeština', languageCode: 'cs' },
	{ label: 'Swedish', description: 'Svenska', languageCode: 'sv' },
	{ label: 'Norwegian', description: 'Norsk', languageCode: 'no' },
	{ label: 'Danish', description: 'Dansk', languageCode: 'da' },
	{ label: 'Finnish', description: 'Suomi', languageCode: 'fi' },
	{ label: 'Hungarian', description: 'Magyar', languageCode: 'hu' },
	{ label: 'Romanian', description: 'Română', languageCode: 'ro' },
	{ label: 'Ukrainian', description: 'Українська', languageCode: 'uk' },
	{ label: 'Hebrew', description: 'עברית', languageCode: 'he' },
	{ label: 'Persian', description: 'فارسی', languageCode: 'fa' },
	{ label: 'Bengali', description: 'বাংলা', languageCode: 'bn' },
	{ label: 'Tamil', description: 'தமிழ்', languageCode: 'ta' },
	{ label: 'Telugu', description: 'తెలుగు', languageCode: 'te' },
	{ label: 'Malayalam', description: 'മലയാളം', languageCode: 'ml' },
	{ label: 'Kannada', description: 'ಕನ್ನಡ', languageCode: 'kn' },
	{ label: 'Marathi', description: 'मराठी', languageCode: 'mr' },
	{ label: 'Gujarati', description: 'ગુજરાતી', languageCode: 'gu' },
	{ label: 'Punjabi', description: 'ਪੰਜਾਬੀ', languageCode: 'pa' },
	{ label: 'Urdu', description: 'اردو', languageCode: 'ur' },
	{ label: 'Kazakh', description: 'Қазақ', languageCode: 'kk' },
	{ label: 'Uzbek', description: 'Oʻzbek', languageCode: 'uz' },
	{ label: 'Azerbaijani', description: 'Azərbaycan', languageCode: 'az' },
	{ label: 'Georgian', description: 'ქართული', languageCode: 'ka' },
	{ label: 'Armenian', description: 'Հայերեն', languageCode: 'hy' },
	{ label: 'Lithuanian', description: 'Lietuvių', languageCode: 'lt' },
	{ label: 'Latvian', description: 'Latviešu', languageCode: 'lv' },
	{ label: 'Estonian', description: 'Eesti', languageCode: 'et' },
	{ label: 'Slovak', description: 'Slovenčina', languageCode: 'sk' },
	{ label: 'Slovenian', description: 'Slovenščina', languageCode: 'sl' },
	{ label: 'Croatian', description: 'Hrvatski', languageCode: 'hr' },
	{ label: 'Serbian', description: 'Српски', languageCode: 'sr' },
	{ label: 'Bulgarian', description: 'Български', languageCode: 'bg' },
	{ label: 'Macedonian', description: 'Македонски', languageCode: 'mk' },
	{ label: 'Albanian', description: 'Shqip', languageCode: 'sq' },
	{ label: 'Basque', description: 'Euskara', languageCode: 'eu' },
	{ label: 'Catalan', description: 'Català', languageCode: 'ca' },
	{ label: 'Galician', description: 'Galego', languageCode: 'gl' },
	{ label: 'Welsh', description: 'Cymraeg', languageCode: 'cy' },
	{ label: 'Irish', description: 'Gaeilge', languageCode: 'ga' },
	{ label: 'Scottish Gaelic', description: 'Gàidhlig', languageCode: 'gd' },
	{ label: 'Breton', description: 'Brezhoneg', languageCode: 'br' },
	{ label: 'Icelandic', description: 'Íslenska', languageCode: 'is' },
	{ label: 'Malay', description: 'Bahasa Melayu', languageCode: 'ms' },
	{ label: 'Filipino', description: 'Filipino', languageCode: 'fil' },
	{ label: 'Burmese', description: 'မြန်မာ', languageCode: 'my' },
	{ label: 'Khmer', description: 'ខ្មែរ', languageCode: 'km' },
	{ label: 'Lao', description: 'ລາວ', languageCode: 'lo' },
	{ label: 'Nepali', description: 'नेपाली', languageCode: 'ne' },
	{ label: 'Sinhala', description: 'සිංහල', languageCode: 'si' },
	{ label: 'Amharic', description: 'አማርኛ', languageCode: 'am' },
	{ label: 'Swahili', description: 'Kiswahili', languageCode: 'sw' },
	{ label: 'Afrikaans', description: 'Afrikaans', languageCode: 'af' },
	{ label: 'Zulu', description: 'isiZulu', languageCode: 'zu' },
	{ label: 'Xhosa', description: 'isiXhosa', languageCode: 'xh' }
];